services:
  - type: web
    name: podrelay-api
    env: python
    plan: free
    region: oregon  # or frankfurt, depending on preference
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn relay_api:app --host 0.0.0.0 --port 8080
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    routes:
      - type: http
        source: /
        targetPort: 8080
